# Generated by Django 4.0.2 on 2022-02-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0002_alter_section_parentsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='title',
            field=models.CharField(default='def', max_length=200),
            preserve_default=False,
        ),
    ]
