# Generated by Django 4.0.2 on 2022-02-24 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0003_section_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='parentSection',
        ),
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='sections.section'),
        ),
    ]
