# Generated by Django 4.0.2 on 2022-02-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0006_alter_section_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
